const REPORT_API='http://127.0.0.1:8767/api',$=selector=>document.querySelector(selector),yearSelect=$('#reportYear'),quarterSelect=$('#reportQuarter'),ownerSelect=$('#reportOwner');let periods=[];
const unique=values=>[...new Set(values)],option=(value,label=value)=>`<option value="${value}">${label}</option>`,safeName=value=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70),bool=value=>value===true||value===1,levelColor=level=>({Expert:'7B1FA2',Advanced:'DA291C',Select:'087565'}[level]||'252525');
function refreshYears(){const years=unique(periods.map(row=>Number(row.year))).sort((a,b)=>b-a);yearSelect.innerHTML=years.map(year=>option(year)).join('');refreshQuarters()}
function refreshQuarters(){const year=Number(yearSelect.value),quarters=unique(periods.filter(row=>Number(row.year)===year).map(row=>Number(row.quarter))).sort((a,b)=>b-a);quarterSelect.innerHTML=quarters.map(quarter=>option(quarter,`Q${quarter}`)).join('');refreshOwners()}
function refreshOwners(){const year=Number(yearSelect.value),quarter=Number(quarterSelect.value),owners=unique(periods.filter(row=>Number(row.year)===year&&Number(row.quarter)===quarter).map(row=>row.account_owner)).sort();ownerSelect.innerHTML=option('','Selecione o Account Owner')+owners.map(owner=>option(owner)).join('');updateSelection()}
async function updateSelection(){const owner=ownerSelect.value,year=Number(yearSelect.value),quarter=Number(quarterSelect.value),button=$('#exportOwnerPptx');button.disabled=!owner;$('#reportPeriod').textContent=`● SQLite · ${year} Q${quarter}`;if(!owner){$('#reportSummary').textContent='Selecione um Account Owner';return}$('#reportSummary').textContent='Consultando quantidade de canais...';try{const rows=await fetch(`${REPORT_API}/partners?year=${year}&quarter=${quarter}&owner=${encodeURIComponent(owner)}`).then(response=>response.json());$('#reportSummary').textContent=`${rows.length} canais serão incluídos no relatório`}catch(error){$('#reportSummary').textContent='Não foi possível consultar os canais'}}
function addHeader(slide,period,owner,index,total){slide.addShape('rect',{x:0,y:0,w:13.333,h:.12,fill:{color:'DA291C'},line:{color:'DA291C'}});slide.addText(`ENGAGE · PARTNER INTELLIGENCE · Q${period.quarter} · ${period.year}`,{x:.6,y:.3,w:7.5,h:.25,fontFace:'Arial',fontSize:14,bold:true,color:'252525',margin:0});slide.addText(owner,{x:8.25,y:.3,w:4.45,h:.25,fontFace:'Arial',fontSize:10,color:'6B6B6B',align:'right',margin:0,fit:'shrink'});if(index)slide.addText(`${index} / ${total}`,{x:11.65,y:7.12,w:1.05,h:.16,fontFace:'Arial',fontSize:7,color:'888888',align:'right',margin:0})}
function addCard(slide,pptx,x,y,w,h,title,value,accent='252525',valueSize=18){slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h,fill:{color:'FFFFFF'},line:{color:'DDDDDD',width:1}});slide.addText(title.toUpperCase(),{x:x+.2,y:y+.16,w:w-.4,h:.2,fontFace:'Arial',fontSize:9,bold:true,color:'6B6B6B',margin:0});slide.addText(value,{x:x+.2,y:y+.48,w:w-.4,h:h-.6,fontFace:'Arial',fontSize:valueSize,bold:true,color:accent,margin:0,fit:'shrink'})}
function complianceInfo(channel){const outside=[];if(!bool(channel.integrator))outside.push('Integrador');if(bool(channel.mssp_account)&&!bool(channel.mssp))outside.push('MSSP');return outside.length?{text:`${outside.join(' e ')} fora do compliance`,negative:true}:{text:'Em compliance',negative:false}}
function pendingText(row){if(!row)return'Sem pendências';if(!row.has_exam_data)return'Aguardando carga de exames';if(!row.deficits?.length)return'Critérios atendidos; revisar status';return row.deficits.map(item=>`${item.certification}: ${item.actual} de ${item.required}`).join(' · ')}
function addSpecializationGrid(slide,pptx,items){items.forEach((item,index)=>{const col=index%2,row=Math.floor(index/2),x=.6+col*6.12,y=3.45+row*.46,w=5.92,h=.36;slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h,fill:{color:item.eligible?'E6F7F3':'F6F9FA'},line:{color:item.eligible?'BCE9DF':'DCE6EC',width:.7}});slide.addText(item.name,{x:x+.14,y:y+.1,w:3.95,h:.15,fontFace:'Arial',fontSize:9,bold:true,color:'252525',margin:0,fit:'shrink'});slide.addText(item.eligible?'✓ Elegível':'Não elegível',{x:x+4.18,y:y+.1,w:1.58,h:.15,fontFace:'Arial',fontSize:8,bold:true,color:item.eligible?'087565':'7E8B98',align:'right',margin:0})})}
function addChannelSlide(pptx,channel,specialization,diagnostics,certification,period,owner,index,total){
 const slide=pptx.addSlide();slide.background={color:'F4F5F6'};addHeader(slide,period,owner,index,total);const compliance=complianceInfo(channel);
 slide.addText('RESULTADO DA CONSULTA',{x:.6,y:.78,w:3.5,h:.2,fontFace:'Arial',fontSize:10,bold:true,color:'DA291C',charSpacing:1.2,margin:0});
 slide.addText(channel.channel,{x:.6,y:1.08,w:12.1,h:.58,fontFace:'Arial',fontSize:20,bold:true,color:'252525',margin:0,fit:'shrink'});slide.addText(`Q${period.quarter} · ${period.year} · ${owner}`,{x:.6,y:1.75,w:12,h:.25,fontFace:'Arial',fontSize:11,color:'6B6B6B',margin:0});
 addCard(slide,pptx,.6,2.1,2.3,.88,'Nível',channel.level,levelColor(channel.level),14);addCard(slide,pptx,3.1,2.1,4.1,.88,'Compliance geral',compliance.text,compliance.negative?'C62828':'087565',14);addCard(slide,pptx,7.4,2.1,5.33,.88,'Compliance: Modelo de negócio',`Integrador: ${bool(channel.integrator)?'Sim':'Não'} · MSSP: ${bool(channel.mssp_account)?(bool(channel.mssp)?'Sim':'Não'):'Não habilitado'}`,'252525',14);
 const specNames={sd_wan:'SD-WAN',sase:'SASE',secure_networking_lan:'Secure Networking LAN',cloud_security:'Cloud Security',secure_networking_firewall:'Secure Networking Firewall',security_operations:'Security Operations',ot:'OT'},items=Object.entries(specNames).map(([field,name])=>({name,eligible:bool(specialization?.[field])})),eligibleCount=items.filter(item=>item.eligible).length;
 slide.addText('Status das especializações',{x:.6,y:3.15,w:5,h:.25,fontFace:'Arial',fontSize:17,bold:true,color:'252525',margin:0});slide.addText(`${eligibleCount} de 7 elegíveis`,{x:10.1,y:3.17,w:2.63,h:.2,fontFace:'Arial',fontSize:10,bold:true,color:'DA291C',align:'right',margin:0});addSpecializationGrid(slide,pptx,items);
 const integrator=diagnostics.integrator.find(row=>row.channel===channel.channel),mssp=diagnostics.mssp.find(row=>row.channel===channel.channel),pending=[];if(integrator)pending.push(`Integrador — ${pendingText(integrator)}`);if(mssp)pending.push(`MSSP — ${pendingText(mssp)}`);
 slide.addText('Pendências de certificação',{x:.6,y:5.33,w:5,h:.25,fontFace:'Arial',fontSize:16,bold:true,color:'252525',margin:0});slide.addText(pending.length?pending.join('\n'):'Sem pendências de certificação',{x:.6,y:5.66,w:12.1,h:.55,fontFace:'Arial',fontSize:12,bold:!pending.length,color:pending.length?'6B6B6B':'087565',margin:0,fit:'shrink'});
 const certs=certification?.has_exam_data?Object.entries(certification.actual).filter(([,count])=>count>0).map(([name,count])=>`${name}: ${count}`):[],certY=pending.length>1?6.6:6.25;slide.addText('Certificações existentes',{x:.6,y:certY,w:5,h:.22,fontFace:'Arial',fontSize:15,bold:true,color:'252525',margin:0});slide.addText(certs.length?certs.join('  ·  '):(certification?.has_exam_data?'Nenhuma certificação encontrada':'Aguardando carga de exames'),{x:.6,y:certY+.3,w:12.1,h:.22,fontFace:'Arial',fontSize:11,color:'6B6B6B',margin:0,fit:'shrink'});slide.addText('Relatório consolidado do programa Engage',{x:.6,y:7.18,w:5,h:.1,fontFace:'Arial',fontSize:7,color:'888888',margin:0})
}
async function exportReport(){const owner=ownerSelect.value,period={year:Number(yearSelect.value),quarter:Number(quarterSelect.value)},button=$('#exportOwnerPptx'),status=$('#reportStatus');if(!owner)return;button.disabled=true;status.textContent='Preparando dados e criando a apresentação...';try{const query=`year=${period.year}&quarter=${period.quarter}&owner=${encodeURIComponent(owner)}`,[channels,specializations,diagnostics,certifications]=await Promise.all([fetch(`${REPORT_API}/partners?${query}`).then(response=>response.json()),fetch(`${REPORT_API}/specializations?${query}`).then(response=>response.json()),fetch(`${REPORT_API}/compliance-diagnostics?${query}`).then(response=>response.json()),fetch(`${REPORT_API}/certifications?${query}`).then(response=>response.json())]);if(!channels.length)throw new Error('Nenhum canal encontrado para os filtros selecionados.');const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author='Engage Partner Intelligence';pptx.subject='Relatório consolidado por Account Owner';pptx.title=`${owner} · Q${period.quarter} ${period.year}`;const cover=pptx.addSlide();cover.background={color:'F4F5F6'};addHeader(cover,period,owner,0,channels.length);cover.addText('RELATÓRIO DE PORTFÓLIO',{x:.7,y:1.2,w:4.7,h:.3,fontFace:'Arial',fontSize:13,bold:true,color:'DA291C',charSpacing:1.2,margin:0});cover.addText(owner,{x:.7,y:1.75,w:11.9,h:1.05,fontFace:'Arial',fontSize:34,bold:true,color:'252525',margin:0,fit:'shrink'});cover.addText(`Q${period.quarter} · ${period.year}`,{x:.7,y:3.05,w:4,h:.4,fontFace:'Arial',fontSize:19,color:'6B6B6B',margin:0});addCard(cover,pptx,.7,4.05,3.2,1.25,'Canais incluídos',String(channels.length),'DA291C');const fullCompliance=channels.filter(channel=>!complianceInfo(channel).negative).length;addCard(cover,pptx,4.15,4.05,3.8,1.25,'Em compliance',String(fullCompliance),'087565');addCard(cover,pptx,8.2,4.05,4.4,1.25,'Fora do compliance',String(channels.length-fullCompliance),'C62828');cover.addText('Cada slide apresenta o status completo de um canal.',{x:.7,y:6.35,w:8,h:.3,fontFace:'Arial',fontSize:14,color:'6B6B6B',margin:0});channels.forEach((channel,index)=>addChannelSlide(pptx,channel,specializations.find(row=>row.channel===channel.channel),diagnostics,certifications.find(row=>row.channel===channel.channel),period,owner,index+1,channels.length));await pptx.writeFile({fileName:`relatorio-${safeName(owner)}-${period.year}-Q${period.quarter}.pptx`});status.textContent=`Relatório criado com ${channels.length} canais e ${channels.length+1} slides.`}catch(error){console.error(error);status.textContent=error.message||'Não foi possível gerar o relatório.'}finally{button.disabled=false}}
yearSelect.addEventListener('change',refreshQuarters);quarterSelect.addEventListener('change',refreshOwners);ownerSelect.addEventListener('change',updateSelection);$('#exportOwnerPptx').addEventListener('click',exportReport);fetch(`${REPORT_API}/periods`).then(response=>response.json()).then(rows=>{periods=rows;refreshYears()}).catch(()=>{$('#reportStatus').textContent='Não foi possível carregar os períodos disponíveis.'});
