var overviewChannels=[],overviewSpecializationRows=[];
const API='http://127.0.0.1:8767/api',ownerFilter=document.querySelector('#ownerFilter'),yearFilter=document.querySelector('#yearFilter'),quarterFilter=document.querySelector('#quarterFilter'),engagementLevelFilter=document.querySelector('#engagementLevelOverviewFilter'),setText=(id,value)=>document.querySelector(id).textContent=value;
function renderOverview(){const owner=ownerFilter.value,rows=owner?overviewChannels.filter(x=>x.owner===owner):overviewChannels,total=rows.length,compliant=rows.filter(x=>x.integrator&&(!x.msspAccount||x.mssp)).length,nonCompliant=rows.filter(x=>!x.integrator).length,mssp=rows.filter(x=>x.msspAccount).length,pending=rows.filter(x=>x.msspAccount&&!x.mssp).length,levels={Select:0,Advanced:0,Expert:0};rows.forEach(x=>levels[x.level]=(levels[x.level]||0)+1);setText('#totalChannels',total);setText('#compliantChannels',compliant);setText('#compliantRate',total?Math.round(compliant/total*100)+'% da seleção':'Sem canais');setText('#nonCompliantChannels',nonCompliant);setText('#nonCompliantRate',total?Math.round(nonCompliant/total*100)+'% da seleção':'Sem canais');setText('#msspAccounts',mssp);setText('#msspRate',total?Math.round(mssp/total*100)+'% da seleção':'Sem canais');setText('#msspPending',pending);setText('#levelSelect',levels.Select);setText('#levelAdvanced',levels.Advanced);setText('#levelExpert',levels.Expert);[['Select','#barSelect'],['Advanced','#barAdvanced'],['Expert','#barExpert']].forEach(([name,id])=>{document.querySelector(id).style.width=(total?levels[name]/total*100:0)+'%';document.querySelector(id).closest('.bar-row').hidden=!!engagementLevelFilter.value&&name!==engagementLevelFilter.value});setText('#ownerContext',owner?total+' canais sob responsabilidade':'Exibindo toda a base');window.dispatchEvent(new CustomEvent('engage:filter',{detail:{owner,rows}}));}
async function loadPeriod(){const year=yearFilter.value,quarter=quarterFilter.value,[partners,specializations]=await Promise.all([fetch(`${API}/partners?year=${year}&quarter=${quarter}`).then(r=>r.json()),fetch(`${API}/specializations?year=${year}&quarter=${quarter}`).then(r=>r.json())]);overviewChannels=partners.map(x=>({channel:x.channel,level:x.level,integrator:!!x.integrator,msspAccount:!!x.mssp_account,mssp:!!x.mssp,owner:x.owner}));overviewSpecializationRows=specializations;const owners=[...new Set(overviewChannels.map(x=>x.owner))].sort((a,b)=>a.localeCompare(b));ownerFilter.innerHTML='<option value="">Todos os Account Owners</option>'+owners.map(x=>`<option value="${x}">${x}</option>`).join('');renderOverview();window.dispatchEvent(new Event('engage:data'));}
window.dashboardReady=(async()=>{const periods=await fetch(`${API}/periods`).then(r=>r.json());const years=[...new Set(periods.map(x=>x.year))].sort((a,b)=>b-a);yearFilter.innerHTML=years.map(x=>`<option value="${x}">${x}</option>`).join('');function quarters(){const qs=[...new Set(periods.filter(x=>x.year==yearFilter.value).map(x=>x.quarter))].sort((a,b)=>b-a);quarterFilter.innerHTML=qs.map(x=>`<option value="${x}">Q${x}</option>`).join('')}quarters();yearFilter.addEventListener('change',async()=>{quarters();await loadPeriod()});quarterFilter.addEventListener('change',loadPeriod);ownerFilter.addEventListener('change',renderOverview);engagementLevelFilter.addEventListener('change',renderOverview);await loadPeriod();return true})().catch(e=>{console.error(e);setText('#ownerContext','Banco de dados indisponível');throw e});




